name: New Contract
description: Add a new 1099 contract opportunity for senior developers.
title: "New Contract"
labels: ["new"]
body:
  - type: markdown
    attributes:
      value: |
        ## New Contract Submission

        Submit a new 1099 contract opportunity for our senior developers. All fields marked with * are required.

  - type: input
    id: job_title
    attributes:
      label: Position Title *
      placeholder: e.g. Senior React Developer
    validations:
      required: true

  - type: input
    id: job_url
    attributes:
      label: Contract/Application Link *
      placeholder: e.g. https://company.com/contract/123
    validations:
      required: true

  - type: input
    id: company_name
    attributes:
      label: Company/Client Name *
      placeholder: e.g. TechConsult Inc
    validations:
      required: true

  - type: input
    id: company_url
    attributes:
      label: Company Website
      placeholder: e.g. https://techconsult.com
    validations:
      required: false

  - type: dropdown
    id: client_industry
    attributes:
      label: Client Industry
      multiple: false
      options:
        - Tech
        - Finance
        - Healthcare
        - Government
        - Retail
        - Manufacturing
        - Other
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Location
      description: Default is "Remote - USA" if left blank
      placeholder: e.g. Remote - USA, Hybrid - NYC
    validations:
      required: false

  - type: input
    id: hourly_rate_min
    attributes:
      label: Minimum Hourly Rate ($)
      placeholder: e.g. 85
    validations:
      required: false

  - type: input
    id: hourly_rate_max
    attributes:
      label: Maximum Hourly Rate ($)
      placeholder: e.g. 105
    validations:
      required: false

  - type: dropdown
    id: contract_duration
    attributes:
      label: Contract Duration
      multiple: false
      options:
        - 3 months
        - 6 months
        - 12 months
        - 18 months
        - 24 months
        - Ongoing
    validations:
      required: false

  - type: input
    id: start_date
    attributes:
      label: Start Date
      description: When does the contract begin? (YYYY-MM-DD format)
      placeholder: e.g. 2026-02-15
    validations:
      required: false

  - type: input
    id: tech_stack
    attributes:
      label: Tech Stack
      description: Comma-separated list of technologies
      placeholder: e.g. React, TypeScript, Node.js, AWS
    validations:
      required: false

  - type: input
    id: experience_years_min
    attributes:
      label: Minimum Years Experience
      description: Default is 5 years if left blank
      placeholder: e.g. 5
    validations:
      required: false

  - type: dropdown
    id: clearance_required
    attributes:
      label: Security Clearance Required?
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: dropdown
    id: corp_to_corp
    attributes:
      label: Corp-to-Corp (C2C) Available?
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      multiple: false
      options:
        - Normal
        - High
        - Urgent
    validations:
      required: false
